# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - samplemigrationapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://webapprgsty.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_86bd0c23e65c44e6b2602cb91967f587 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_09f741168b224fe4b3627b53fe39c7a1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.AzureAppService_ContainerUsername_86bd0c23e65c44e6b2602cb91967f587 }}/sample/hello-world:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'samplemigrationapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_de2f8390ad4c481a88bc752dc229f42c }}
        images: 'webapprgsty.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_86bd0c23e65c44e6b2602cb91967f587 }}/sample/hello-world:${{ github.sha }}'